name: Push Base Alpine Image

on:
  push:
    tags:
      - 'app-v[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Version Tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test Version Tag
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Base Alpine Image
      run: |
        docker build --rm -f base.alpine/Dockerfile -t ${{secrets.DOCKER_USER}}/baseimage:${{ env.RELEASE_VERSION }} base.alpine
    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_USER}}/baseimage:${{ env.RELEASE_VERSION }}